### ISSUE TITLE
[sugggestion] on state enter triggered on created

### ISSUE THREAD

**Issue by F3der1co** [armandoalonso/fsm#2]
I know this was also not supported in the old FSM addon, but would be awesome if it could be added. (if possible)

**Comment by armandoalonso** [comment]
Yeah i briefly looked into this, but I was not able to call the trigger in the instance constructor (because the instance is not ready yet). i can try and add an artificial delay which seems kinda hacky? or maybe figure out a way to execute some logic on the next tick when the instance is ready. 

I'll do some testing and see if i can find a suitable solution

**Comment by armandoalonso** [comment]
I found a work around for this as well to trigger the initial on state enter and, on any state, changed conditions.  will have this pushed shortly

**Comment by armandoalonso** [comment]
fixed in v1.0.0.2

**Comment by F3der1co** [comment]
thank you for the bug fix and this enhancement :)
